# Generated by Django 5.0.4 on 2024-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.AddField(
            model_name='maquina',
            name='machineId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='userId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
