# Generated by Django 5.0.4 on 2024-04-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_remove_maquina_id_remove_personal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='machineId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='userId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
