# Generated by Django 5.0.4 on 2024-04-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_alter_maquina_machineid_alter_personal_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('actividad', models.CharField(max_length=255, verbose_name='actividad')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20, verbose_name='tipo')),
                ('realizado', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=3, verbose_name='realizado')),
                ('autorizado', models.CharField(max_length=255, verbose_name='autorizado')),
                ('tiempo', models.IntegerField(verbose_name='tiempo')),
                ('costo', models.FloatField(verbose_name='costo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mantenimiento', to='cmms.maquina')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mantenimiento', to='cmms.personal')),
            ],
        ),
    ]
