# Generated by Django 5.0.4 on 2024-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_ordendemantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='hora'),
        ),
    ]
