# Generated by Django 5.0.4 on 2024-04-24 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_alter_ordendemantenimiento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='hora',
            field=models.TimeField(default=datetime.time(8, 56, 47, 221100), verbose_name='hora'),
        ),
    ]
