# Generated by Django 5.0.4 on 2024-04-24 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_alter_ordendemantenimiento_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendemantenimiento',
            name='id',
        ),
        migrations.AddField(
            model_name='ordendemantenimiento',
            name='reporteId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 3, 21, 47817), verbose_name='hora'),
        ),
    ]
