# Generated by Django 5.0.4 on 2024-04-24 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_remove_ordendemantenimiento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 5, 1, 665137), verbose_name='hora'),
        ),
    ]
