# Generated by Django 5.0.4 on 2024-04-24 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_alter_ordendemantenimiento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 9, 29, 477764), verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='reporteId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
