# Generated by Django 5.0.4 on 2024-04-29 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_alter_ordendemantenimiento_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='actividad',
            field=models.CharField(verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='ordendemantenimiento',
            name='hora',
            field=models.TimeField(default=datetime.time(17, 41, 51, 41131), verbose_name='hora'),
        ),
    ]
